name: Compilar para macOS

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Descarregar o código do repositório
      uses: actions/checkout@v4

    - name: Instalar a Raylib no Mac
      run: |
        brew update
        brew install raylib

    - name: Compilar o Jogo
      run: |
        # Cria a pasta 'mac' na máquina virtual se ela não existir
        mkdir -p mac
        
        g++ -O3 -std=c++17 main.cpp \
        -I/opt/homebrew/include \
        -L/opt/homebrew/lib \
        -lraylib \
        -framework OpenGL \
        -framework Cocoa \
        -framework IOKit \
        -framework CoreVideo \
        -o mac/meu_jogo_mac

    - name: Disponibilizar o Executável para Download
      uses: actions/upload-artifact@v4
      with:
        name: TerrariaDoToinoMacOS
        path: mac/meu_jogo_mac